sudo: required
language: java
jdk: oraclejdk8
services:
- docker
env:
  global:
  - secure: J/ibzMI6E3AHFfPamt6+FpSkqe1xM2F52A2ur5pTp//ZxUyeef0B4bb9fY/1sF70LOjjK4G1V0RYThLmq3Riw59hTq4nTs2GUcfkO9TzBCFtv4omp4S9Mj8SjWn3qrwLRGASdur+ArTVxND4cwNdRUDaLr60KuA9jR2kPe0s+8A6ibNyeBXgmWopyeSUkXcS0/UJD0rZNLSmttLZhUXn0uka93kfIo4ziCdo72VY/RInXX/vWNLCh5DI+KleqzRNFnV5PvcFhFC+LoMl+R1tJyTelY14Bdq71dnaqZGC/a1CLCugv5JFZZZ6eekd/oFh1Zr/3e9Iw6bhXgGkTn2ovjyL+Y9xj85P1jEujmS40E+vgp8gJI3DQHogf2FJPZCVcP2XuiZAHOR9snXZLB1sLuE/jq6OJrnGLsW8BLEOXNzoRJ7wgaSuruX3G8zTAgCSnXaYjPICm8n9ziPc3fxHqhWgxSGhfWZvFoPFl01NUOyBxb/HLSeLxeE7NSDG67PKi6yvwV0sLTN71TzUyxWDk/12uWAWYR2+Gjix4e2W1/JXc9h8RmzSuK/bNasLrwcJ5e5hU0v4ltHQjFzdButmdAc21CS1kcTLQqZajP66sJMbW5lXV7fr1OB7EJZso/QWOJn3Zjkw2qsJcGT2J6gmRJyWhxi4f4vlhv6dmO9hN9Q=
  - secure: cUQGvN/7y36ykLJjnriok7qY94UvZlnqW0lUL4CeM29aaf/oz2YvXYLMu6msmt0eb1h1xa5SKZcXPRTj7SFPGCvT1fjt7IwNzncdNEQe3UOFnKHJU7BGbDFrZko1Mz8+Ugul4phjGK+CwZAMzwYa5pR8e2xJPXFuIG8Vn8sef73PZLgwpwjmJJETDdxqRRpg5ZjAUMMKAbu9DkjF2iN3HELWc9+jWjjmoucnkbrDSonYZkpxqXDAwrSKASuND00ykD+ZtKEZECgr2yxposmrufC3gPFbix9/hPYLZcBV77Kg8j6hfHd33k/Lc+lyJdKkq9kw9PYJhwrZAoapnCBjzkkbsBmqbr+Fkimp7r4S6WMgBGErak9ZXodsSVXDKZf4EmLB6Ldq6LDQXiEq31n6hoAz3bt5pAJxTKrRvTN6stUfI82y/FyadQYTva0SUD2J07lXs/wA8JjnA0HrvRQRDM339RXza6ss/i3y6KvxsLL8BKYm5hrMuNGxWfH8BaGdav4s8V2urUltN0D3UcioYmScomJuyHnhQ8UWfKefu6HitGNRQr4KorYLRalSbOEXlbi6zXOnahvNSD6pmVCvT+jMyGCHWkqGsw84ImGrJMx/DiYN/D/coWe3PJ16FFZ7dIfDm9lgChubvuGnsIs0o8wO0TtEaGAzvnj0+x7HHIE=
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
- export IMAGE_NAME=leshkasmirnov/eng_bot
- docker build -t $IMAGE_NAME:$COMMIT .
- docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME